# Generated by Django 4.0.6 on 2022-07-13 21:18

from django.db import migrations, models
import django.db.models.deletion
import hammer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.PositiveBigIntegerField()),
                ('asn_status', models.SmallIntegerField(choices=[(-1, 'Clear'), (0, 'Unchecked'), (1, 'Banned')], default=0)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, validators=[hammer.models.validate_ip_range])),
                ('range_start', models.BinaryField(max_length=35)),
                ('range_end', models.BinaryField(max_length=35)),
                ('scheduled', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('check_reason', models.TextField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hammer.asn')),
            ],
        ),
    ]
