# Generated by Django 4.0.6 on 2022-07-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hammer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprange',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hammer.asn'),
        ),
    ]
